### ISSUE TITLE
Not working after reboot

### ISSUE THREAD

**Issue by Petrux25** [tegan-lamoureux/Rotate-Spectre#4]
Hello! The script works absolutely fantastic on my laptop but, after I restart it doesn't start with the rc.local file. I tried with chmod 777 on both files  but nothing works
This is my current rc.local file:
```
#!/bin/sh -e
# rc.local
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
# In order to enable or disable this script just change the execution
# bits.
# By default this script does nothing.

sudo python2.7 /etc/rotate.py &
exit 0
```

After checking `systemctl status rc-local.service` it returned this 

```
rc-local.service - /etc/rc.local Compatibility
   Loaded: loaded (/lib/systemd/system/rc-local.service; static; vendor preset: enabled)
  Drop-In: /lib/systemd/system/rc-local.service.d
           └─debian.conf
   Active: active (exited) (Result: exit-code) since vie 2018-03-09 09:56:07 CST; 1min 41s ago
  Process: 1051 ExecStart=/etc/rc.local start (code=exited, status=0/SUCCESS)
 Main PID: 1052 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/rc-local.service

mar 09 09:56:07 diego-HP-Spectre-x360-Convertible-13-ac0XX rc.local[1051]: Traceback (most recent call last):
mar 09 09:56:07 diego-HP-Spectre-x360-Convertible-13-ac0XX rc.local[1051]:   File "/etc/rotate.py", line 90, in <module>
mar 09 09:56:07 diego-HP-Spectre-x360-Convertible-13-ac0XX rc.local[1051]:     rotate(i)
mar 09 09:56:07 diego-HP-Spectre-x360-Convertible-13-ac0XX rc.local[1051]:   File "/etc/rotate.py", line 59, in rotate
mar 09 09:56:07 diego-HP-Spectre-x360-Convertible-13-ac0XX rc.local[1051]:     check_call(['xrandr', '-o', s['rot']])
mar 09 09:56:07 diego-HP-Spectre-x360-Convertible-13-ac0XX rc.local[1051]:   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
mar 09 09:56:07 diego-HP-Spectre-x360-Convertible-13-ac0XX rc.local[1051]:     raise CalledProcessError(retcode, cmd)
mar 09 09:56:07 diego-HP-Spectre-x360-Convertible-13-ac0XX rc.local[1051]: subprocess.CalledProcessError: Command '['xrandr', '-o', 'normal']' return
mar 09 09:56:07 diego-HP-Spectre-x360-Convertible-13-ac0XX sudo[1052]: pam_unix(sudo:session): session closed for user root
mar 09 09:56:07 diego-HP-Spectre-x360-Convertible-13-ac0XX systemd[1]: rc-local.service: Main process exited, code=exited, status=1/FAILURE
```
I appreciate any help! 
Thanks

**Comment by tegan-lamoureux** [comment]
Hmm, I'm not actually too familiar with using rc.local, as I only really run Arch Linux. I know system scripts like that can be really tricky with paths, maybe try using the direct path to python2.7 instead of just the command in your file? e.g. `sudo /usr/bin/python2.7 /etc/rotate.py &`, or wherever it's located.

Actually, now that I think about it, it's probably a bad idea to use rc.local, as that might run before xorg is up and running? That would cause it to fail. Maybe try adding it to your .xinitrc file, if your distro uses that. Or the utility provided by your WM/DE to run things on startup?
